<a href="https://colab.research.google.com/github/AmanPhadke/DataScience_Journey/blob/main/Phase1/Week1_NumPy/100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
!pip install -r requirements.txt
!pip install generators

  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Created wheel for generators: filename=generators-2020.4.27-py3-none-any.whl size=42860 sha256=d72d73e9692cc66cd4189d46b340279c8b4ef019ba9b6012dd70b8eb249741ed
  Stored in directory: /root/.cache/pip/wheels/ec/4d/f8/15b85af5b79dfe54f9517172ad9e4767ea0e1fb1b42d5637b6
  Created wheel for strict_functions: filename=strict_functions-2020.2.4-py3-none-any.whl size=15451 sha256=a89f9707a5c0f226c4793b86383a422238735c7e539e4542ddcae5ac544955d3
  Stored in directory: /root/.cache/pip/wheels/c1/8f/21/91f158d19bdb5cf07e08b48ffc567a5e960e542f495f15977b
Successfully built generators strict_functions


In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np
import generators as gen

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
np.__version__

'2.0.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
a = np.zeros(10, dtype = 'int32')
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
a.nbytes

40

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
b = np.zeros(10, dtype = 'int32')
b[4] = 1
b

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int32)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
c = np.arange(10,50)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
a = np.zeros((3,3))
a[2,2] = 1

np.flip(a)

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
b= np.arange(0, 9)
b.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
a = np.array([1,2,0,0,4,0])
# for element in a:
#   if (element == 0):
#     pass
#   else:
#     print(np.where(a == element))

# b = np.nonzero(a)

b = np.where( a == 0)
b

(array([2, 3, 5]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
i = np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
np.random.rand(3,3,3)

array([[[0.22580712, 0.80430462, 0.47580189],
        [0.43942574, 0.34231077, 0.24479654],
        [0.46591659, 0.61851789, 0.04124942]],

       [[0.36654918, 0.79515436, 0.07669389],
        [0.40129849, 0.37408349, 0.64855863],
        [0.30500783, 0.54404022, 0.75614486]],

       [[0.86860457, 0.00943084, 0.2428737 ],
        [0.50434055, 0.10115173, 0.07837275],
        [0.26122957, 0.24788199, 0.01734413]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
a = np.random.randn(10,10)
min_val = np.min(a)
max_val = np.max(a)
print(max_val, min_val)

2.5219042730661405 -3.1941032238058495


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
m = np.random.randn(30)
print(np.mean(m))

0.03057220007744279


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
output = np.ones((3,3))
output[1,1] = 0
output


array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
e_array = np.ones((3,3))
# z_array = np.zeros((5,5))
# z_array[1:-1,1:-1] = e_array
# print(z_array)

n= np.pad(e_array, 1)
n

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
matrix = np.arange(1,5)
diag = np.diag(matrix, k=-1)
diag

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
check = np.zeros((8,8))
check[::2, ::2] = 1
check[1::2, 1::2] = 1
check

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
np.unravel_index(99, (6,7,8))


(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
a = np.array([1,0])
a1 = np.tile(a, 4)
b = np.array([0,1])
b1 = np.tile(b, 4)
np.vstack((a1,b1,a1,b1,a1,b1,a1,b1))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
rng = np.random.default_rng()
x = rng.integers(100, size =(5,5))

#with min-max scaling
min_val = x.min(axis=0)
max_val = x.max(axis=0)


norm1 = (x - min_val) / (max_val - min_val)

print(norm1)

#With standardization
mean = x.mean(axis=0)
std = x.std(axis=0)


norm2 = ( x - mean ) / std
norm2 = norm2.astype('int32')
print(norm2)


[[0.56578947 1.         1.         0.78571429 0.        ]
 [0.75       0.17857143 0.         1.         0.44444444]
 [0.28947368 0.         0.8255814  0.66666667 1.        ]
 [0.         0.85714286 0.95348837 0.         0.75      ]
 [1.         0.60714286 0.84883721 0.36904762 0.25      ]]
[[ 0  1  0  0 -1]
 [ 0  0 -1  1  0]
 [ 0 -1  0  0  1]
 [-1  0  0 -1  0]
 [ 1  0  0  0  0]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
rgb_dtype = np.dtype([
        ('R', 'u1'),
        ('G', 'u1'),
        ('B', 'u1'),
        ('A', 'u1')
    ])


color = np.array([(255,0,0,255)], dtype = rgb_dtype)

color

array([(255, 0, 0, 255)],
      dtype=[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
rng = np.random.default_rng()
a = rng.integers(10, size = (5,3))
b = rng.integers(10, size = (3,2))
c = a @ b
print("A Matrix: \n", a)
print("B Matrix: \n", b)
print("C Matrix: \n", c)

A Matrix: 
 [[6 8 8]
 [6 7 3]
 [3 6 4]
 [0 5 4]
 [1 6 9]]
B Matrix: 
 [[6 8]
 [0 2]
 [3 7]]
C Matrix: 
 [[ 60 120]
 [ 45  83]
 [ 30  64]
 [ 12  38]
 [ 33  83]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
between = ((a > 3) & (a < 8))
a[between] *= -1
a

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array([np.nan]).astype(int).astype(float)

/tmp/ipython-input-699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
arr = np.array([1.4, 5.6, -1.8, -4.3, -3.3, 5.6 ])
np.where( arr > 0, np.ceil(arr), np.floor(arr))

array([ 2.,  6., -2., -5., -4.,  6.])

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
one = np.arange(5)
two = np.arange(5)

np.where(one == two)


(array([0, 1, 2, 3, 4]),)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today = np.datetime64('today','D')
yesterday = today - np.timedelta64(1)
tomorrow = today + np.timedelta64(1)

print(today ,'\n', yesterday,'\n', tomorrow)

2025-10-18 
 2025-10-17 
 2025-10-19


#

### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
july = np.arange('2016-07-01','2016-08-01', dtype= 'datetime64[D]')
july

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
a = np.arange(10)
b = np.arange(10)
c = a + b
d = (-a)/2
print(c*d)

np.add(a,b)
np.negative(a,out=a)
np.divide(a,2)
print(np.multiply(a,b))


[  0.  -1.  -4.  -9. -16. -25. -36. -49. -64. -81.]
[  0  -1  -4  -9 -16 -25 -36 -49 -64 -81]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)